domain: jellyo1.github.io
url: "https://jellyo1.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "ToBeDefined Home" # the name of your site, e.g. ACME Corp.

sass:
  load_paths:
    - _sass
    - node_modules

  include: ["node_modules/tailwindcss"]

assets:
  sources:
    - assets/fonts
    - assets/images

postcss:
  cache: false

plugins:
  - jekyll-postcss-v2